//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SERWIS.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StudenciEntities : DbContext
    {
        public StudenciEntities()
            : base("name=StudenciEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Oceny> Ocenies { get; set; }
        public virtual DbSet<Student> Students { get; set; }
    
        public virtual ObjectResult<Show_All_Result> Show_All()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Show_All_Result>("Show_All");
        }
    
        public virtual ObjectResult<Show_Oceny_Result> Show_Oceny()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Show_Oceny_Result>("Show_Oceny");
        }
    
        public virtual ObjectResult<Show_Osoby_Result> Show_Osoby()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Show_Osoby_Result>("Show_Osoby");
        }
    }
}
