//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SERWIS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oceny
    {
        public int id_oceny { get; set; }
        public int id_indeks { get; set; }
        public int ocena { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
